// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1:string):Promise<boolean>;

export function GetLastCanvasPath():Promise<string>;

export function LoadCanvas():Promise<string>;

export function LoadCanvasFrom():Promise<string>;

export function SaveCanvas(arg1:string):Promise<void>;

export function SaveCanvasAs(arg1:string):Promise<string>;

export function SaveCanvasToPath(arg1:string,arg2:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectOutputFile():Promise<string>;

export function StartPipeline(arg1:string,arg2:string,arg3:boolean,arg4:Array<any>):Promise<string>;
