// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetLastCanvasPath() {
  return window['go']['main']['App']['GetLastCanvasPath']();
}

export function LoadCanvas() {
  return window['go']['main']['App']['LoadCanvas']();
}

export function LoadCanvasFrom() {
  return window['go']['main']['App']['LoadCanvasFrom']();
}

export function SaveCanvas(arg1) {
  return window['go']['main']['App']['SaveCanvas'](arg1);
}

export function SaveCanvasAs(arg1) {
  return window['go']['main']['App']['SaveCanvasAs'](arg1);
}

export function SaveCanvasToPath(arg1, arg2) {
  return window['go']['main']['App']['SaveCanvasToPath'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectOutputFile() {
  return window['go']['main']['App']['SelectOutputFile']();
}

export function StartPipeline(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPipeline'](arg1, arg2, arg3, arg4);
}
